function if_actor_has_agr_safe_container_1(first_speaker, second_speaker)
	return first_speaker:object("agr_safe_container_1") ~= nil
end

function if_actor_hasnt_agr_safe_container_1(first_speaker, second_speaker)
	return not if_actor_has_agr_safe_container_1(first_speaker, second_speaker)
end

function transfer_agr_safe_container_1(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "agr_safe_container_1")
end



function if_actor_has_dev_flash_agru(first_speaker, second_speaker)
	return first_speaker:object("dev_flash_agru") ~= nil
end

function if_actor_hasnt_dev_flash_agru(first_speaker, second_speaker)
	return not if_actor_has_dev_flash_agru(first_speaker, second_speaker)
end

function transfer_dev_flash_agru(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "dev_flash_agru")
end



function if_actor_has_dev_document_1_x18(first_speaker, second_speaker)
	return first_speaker:object("dev_document_1_x18") ~= nil
end

function if_actor_hasnt_dev_document_1_x18(first_speaker, second_speaker)
	return not if_actor_has_dev_document_1_x18(first_speaker, second_speaker)
end

function transfer_dev_document_1_x18(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "dev_document_1_x18")
end

function if_actor_has_dev_document_2_x18(first_speaker, second_speaker)
	return first_speaker:object("dev_document_2_x18") ~= nil
end

function if_actor_hasnt_dev_document_2_x18(first_speaker, second_speaker)
	return not if_actor_has_dev_document_2_x18(first_speaker, second_speaker)
end

function transfer_dev_document_2_x18(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "dev_document_2_x18")
end

function if_actor_has_dev_document_3_x18(first_speaker, second_speaker)
	return first_speaker:object("dev_document_3_x18") ~= nil
end

function if_actor_hasnt_dev_document_3_x18(first_speaker, second_speaker)
	return not if_actor_has_dev_document_3_x18(first_speaker, second_speaker)
end

function transfer_dev_document_3_x18(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "dev_document_3_x18")
end