function give_money_to_actor_1000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 1000)
end

function if_actor_has_maney_1000(first_speaker, second_speaker)
	return getLocalActor():money() >= 1000
end

function transfer_1000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 1000)
end

function give_money_to_actor_2000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 2000)
end

function if_actor_has_maney_2000(first_speaker, second_speaker)
	return getLocalActor():money() >= 2000
end

function transfer_2000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 2000)
end

function give_money_to_actor_3000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 3000)
end

function if_actor_has_maney_3000(first_speaker, second_speaker)
	return getLocalActor():money() >= 3000
end

function transfer_3000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 3000)
end

function give_money_to_actor_4000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 4000)
end

function if_actor_has_maney_4000(first_speaker, second_speaker)
	return getLocalActor():money() >= 4000
end

function transfer_4000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 4000)
end

function give_money_to_actor_5000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 5000)
end

function if_actor_has_maney_5000(first_speaker, second_speaker)
	return getLocalActor():money() >= 5000
end

function transfer_5000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 5000)
end

function give_money_to_actor_6000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 6000)
end

function if_actor_has_maney_6000(first_speaker, second_speaker)
	return getLocalActor():money() >= 6000
end

function transfer_6000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 6000)
end

function give_money_to_actor_7000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 7000)
end

function if_actor_has_maney_7000(first_speaker, second_speaker)
	return getLocalActor():money() >= 7000
end

function transfer_7000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 7000)
end

function give_money_to_actor_8000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 8000)
end

function if_actor_has_maney_8000(first_speaker, second_speaker)
	return getLocalActor():money() >= 8000
end

function transfer_8000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 8000)
end

function give_money_to_actor_9000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 9000)
end

function if_actor_has_maney_9000(first_speaker, second_speaker)
	return getLocalActor():money() >= 9000
end

function transfer_9000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 9000)
end

function give_money_to_actor_10000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 10000)
end

function if_actor_has_maney_10000(first_speaker, second_speaker)
	return getLocalActor():money() >= 10000
end

function transfer_10000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 10000)
end

function give_money_to_actor_20000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 20000)
end

function if_actor_has_maney_20000(first_speaker, second_speaker)
	return getLocalActor():money() >= 20000
end

function transfer_20000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 20000)
end

function give_money_to_actor_25000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 25000)
end

function if_actor_has_maney_25000(first_speaker, second_speaker)
	return getLocalActor():money() >= 25000
end

function transfer_25000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 25000)
end

function give_money_to_actor_50000(first_speaker, second_speaker)
	dialogs.relocate_money_to_actor(first_speaker, second_speaker, 50000)
end

function if_actor_has_maney_50000(first_speaker, second_speaker)
	return getLocalActor():money() >= 50000
end

function transfer_50000(first_speaker, second_speaker)
	dialogs.relocate_money_from_actor(first_speaker, second_speaker, 50000)
end
