function give_actor_yan_psi_detector(first_speaker, second_speaker)
	dialogs.relocate_item_section_to_actor(first_speaker, second_speaker, "yan_psi_detector")
end

function if_actor_has_yan_psi_detector(first_speaker, second_speaker)
	return first_speaker:object("yan_psi_detector") ~= nil
end

function if_actor_hasnt_yan_psi_detector(first_speaker, second_speaker)
	return not if_actor_has_yan_psi_detector(first_speaker, second_speaker)
end

function transfer_yan_psi_detector(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "yan_psi_detector")
end