
function if_actor_has_medkit(first_speaker, second_speaker)
	return first_speaker:object("medkit") ~= nil
end

function if_actor_hasnt_medkit(first_speaker, second_speaker)
	return not if_actor_has_medkit(first_speaker, second_speaker)
end

function transfer_medkit(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "medkit")
end


function if_actor_has_af_medusa(first_speaker, second_speaker)
	return first_speaker:object("af_medusa") ~= nil
end

function if_actor_hasnt_af_medusa(first_speaker, second_speaker)
	return not if_actor_has_af_medusa(first_speaker, second_speaker)
end

function transfer_af_medusa(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_medusa")
end



function if_actor_has_af_blood(first_speaker, second_speaker)
	return first_speaker:object("af_blood") ~= nil
end

function if_actor_hasnt_af_blood(first_speaker, second_speaker)
	return not if_actor_has_af_blood(first_speaker, second_speaker)
end

function transfer_af_blood(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_blood")
end



function if_actor_has_af_cristall_flower(first_speaker, second_speaker)
	return first_speaker:object("af_cristall_flower") ~= nil
end

function if_actor_hasnt_af_cristall_flower(first_speaker, second_speaker)
	return not if_actor_has_af_cristall_flower(first_speaker, second_speaker)
end

function transfer_af_cristall_flower(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_cristall_flower")
end



function if_actor_has_af_vyvert(first_speaker, second_speaker)
	return first_speaker:object("af_vyvert") ~= nil
end

function if_actor_hasnt_af_vyvert(first_speaker, second_speaker)
	return not if_actor_has_af_vyvert(first_speaker, second_speaker)
end

function transfer_af_vyvert(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_vyvert")
end



function if_actor_has_af_gravi(first_speaker, second_speaker)
	return first_speaker:object("af_gravi") ~= nil
end

function if_actor_hasnt_af_gravi(first_speaker, second_speaker)
	return not if_actor_has_af_gravi(first_speaker, second_speaker)
end

function transfer_af_gravi(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_gravi")
end



function if_actor_has_af_gold_fish(first_speaker, second_speaker)
	return first_speaker:object("af_gold_fish") ~= nil
end

function if_actor_hasnt_af_gold_fish(first_speaker, second_speaker)
	return not if_actor_has_af_gold_fish(first_speaker, second_speaker)
end

function transfer_af_gold_fish(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_gold_fish")
end



function if_actor_has_af_cristall(first_speaker, second_speaker)
	return first_speaker:object("af_cristall") ~= nil
end

function if_actor_hasnt_af_cristall(first_speaker, second_speaker)
	return not if_actor_has_af_cristall(first_speaker, second_speaker)
end

function transfer_af_cristall(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_cristall")
end



function if_actor_has_af_fireball(first_speaker, second_speaker)
	return first_speaker:object("af_fireball") ~= nil
end

function if_actor_hasnt_af_fireball(first_speaker, second_speaker)
	return not if_actor_has_af_fireball(first_speaker, second_speaker)
end

function transfer_af_fireball(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_fireball")
end



function if_actor_has_af_eye(first_speaker, second_speaker)
	return first_speaker:object("af_eye") ~= nil
end

function if_actor_hasnt_af_eye(first_speaker, second_speaker)
	return not if_actor_has_af_eye(first_speaker, second_speaker)
end

function transfer_af_eye(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "af_eye")
end



function if_actor_has_family_gun(first_speaker, second_speaker)
	return first_speaker:object("wpn_toz34_m2") ~= nil
end

function if_actor_hasnt_family_gun(first_speaker, second_speaker)
	return not if_actor_has_family_gun(first_speaker, second_speaker)
end

function transfer_family_gun(first_speaker, second_speaker)
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "wpn_toz34_m2")
end



function if_actor_has_mutant_boar_part_15x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_boar_part" then count = count + 1
				end
			end, nil)
		if count >= 7 then return true
		end
	end
	
	return false
end

function transfer_mutant_boar_part_15x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_boar_part" , 7)
end



function if_actor_has_mutant_dog_part_10x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_dog_part" then count = count + 1
				end
			end, nil)
		if count >= 10 then return true
		end
	end
	
	return false
end

function transfer_mutant_dog_part_10x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_dog_part" , 10)
end



function if_actor_has_mutant_flesh_part_5x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_flesh_part" then count = count + 1
				end
			end, nil)
		if count >= 2 then return true
		end
	end
	
	return false
end

function transfer_mutant_flesh_part_5x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_flesh_part" , 2)
end



function if_actor_has_mutant_psevdodog_part_5x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_psevdodog_part" then count = count + 1
				end
			end, nil)
		if count >= 5 then return true
		end
	end
	
	return false
end

function transfer_mutant_psevdodog_part_5x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_psevdodog_part" , 5)
end



function if_actor_has_mutant_snork_part_4x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_snork_part" then count = count + 1
				end
			end, nil)
		if count >= 4 then return true
		end
	end
	
	return false
end

function transfer_mutant_snork_part_4x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_snork_part" , 4)
end



function if_actor_has_mutant_krovosos_part_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_krovosos_part" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_mutant_krovosos_part_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_krovosos_part" , 3)
end

function if_actor_has_mutant_chimera_part_1x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "mutant_chimera_part" then count = count + 1
				end
			end, nil)
		if count >= 1 then return true
		end
	end
	
	return false
end

function transfer_mutant_chimera_part_1x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "mutant_chimera_part" , 1)
end



function if_actor_has_materials_acetone_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "jup_b200_tech_materials_acetone" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_materials_acetone_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "jup_b200_tech_materials_acetone" , 3)
end

function if_actor_has_materials_capacitor_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "jup_b200_tech_materials_capacitor" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_materials_capacitor_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "jup_b200_tech_materials_capacitor" , 3)
end

function if_actor_has_materials_textolite_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "jup_b200_tech_materials_textolite" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_materials_textolite_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "jup_b200_tech_materials_textolite" , 3)
end

function if_actor_has_materials_transistor_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "jup_b200_tech_materials_transistor" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_materials_transistor_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "jup_b200_tech_materials_transistor" , 3)
end

function if_actor_has_materials_wire_3x(first_speaker, second_speaker)
	local actor = db.mp_actors[LocalActor()]
	local count = 0
	
	if actor ~= nil then
		actor:iterate_inventory(
			function(dummy,item)
				if item:section() == "jup_b200_tech_materials_wire" then count = count + 1
				end
			end, nil)
		if count >= 3 then return true
		end
	end
	
	return false
end

function transfer_materials_wire_3x(first_speaker, second_speaker)	
	dialogs.relocate_item_section_from_actor(first_speaker, second_speaker, "jup_b200_tech_materials_wire" , 3)
end





























